### ISSUE TITLE
API Bump to 8

### ISSUE THREAD

**Issue by adelasm** [Maia-Everett/dalamud-snooper#10]
Hi! My girlfriend and I have been using your plugin a lot for roleplay and have been missing its functionality since the patch. Any chance you'd be able to update to the new API? We perfectly understand it taking the time it takes, just wanted to bump just in case!

**Comment by Maia-Everett** [comment]
Just about to update!

**Comment by adelasm** [comment]
Lovely to hear! Figured as much but wanted to check anyway!

**Comment by Maia-Everett** [comment]
I've submitted version 0.3.1.0 for Dalamud API 8 for approval. Just waiting on the Dalamud admins now!

https://github.com/goatcorp/DalamudPluginsD17/pull/1102
