### ISSUE TITLE
Option to mute sound for ongoing tell

### ISSUE THREAD

**Issue by clytemnestra** [Maia-Everett/dalamud-snooper#18]
Hello there, is it possible to mute the sound for ongoing tells and keep it only for incoming ones? Think this is happening because the latest change https://github.com/Maia-Everett/dalamud-snooper/commit/a4c0e0213fae3e089f6a70cdc3754b949f39eeb5

 It's really annoying when telling with the snooped target

**Comment by Maia-Everett** [comment]
Sound for outgoing tells was not intended, so I've just disabled it for 1.2.1.0. Thanks for the report!
