### ISSUE TITLE
Miscellaneous feedback

### ISSUE THREAD

**Issue by Maia-Everett** [Maia-Everett/dalamud-snooper#2]
> Love this, thank you so much!
> 
> Don't know if you're open to requests, but I'll throw them out there:
> 
> - ~~Option to enable logging other channels (group, tells)~~ Done
> - Option to add more people to a window via names
> - Option to have it clear or remember names on relog
> 
> Thanks again!

**Comment by PrincessRTFM** [comment]
Similar to suggestion 2 on there, I'd like to request the ability to open a "persistent" window that remains attached to the target you had when it was opened. That way, you could target someone, open a snooper, change targets, open a new snooper, repeat as necessary, and have windows to track several people.

Secondarily, I'd like to also request that a single window be able to track _multiple_ targets, maybe? That way, if you're in a group of three or four people in a busy venue, you can watch what just your group is saying without needing to switch targets or track several windows at once, which would be hard to keep in order.

**Comment by gucciBane** [comment]
I don't know if Dalamud context menus are working at this point, but piggy-backing off all of the above and being able to right-click ppl to add them to a window would be pretty awesome. Or maybe through a chat command that could utilize <t>? It's a little awkward having to stare at someone to keep track of what they're saying.

**Comment by Maia-Everett** [comment]
Persistent windows are now implemented in 0.3.0.0, and they persist across game restarts.

As for the third suggestion, I can't make heads or tails of it, so I'll ask the author what they meant. Closing this issue for now.
