### ISSUE TITLE
[Request] option Dates with Timestamp

### ISSUE THREAD

**Issue by decoytrix** [Maia-Everett/dalamud-snooper#23]
Just thought it would be useful to see what the date was when looking through the snooper log.  Options like displaying date with the timestamp, or on the first message of a new day, or as line above the first message of a new day with the date on it.  

I'm sure some of the cleaner options are more difficult to implement, but I'd use any version of the feature, even if it was just to toggle on and off as needed. =D

**Comment by Maia-Everett** [comment]
You posted this issue _rightt_ after I migrated the project to Codeberg! Amazing :)

Could you repost it there?

https://codeberg.org/Linneris/dalamud-snooper/issues

**Comment by decoytrix** [comment]
sure
