### ISSUE TITLE
Plugin may need an update for API7

### ISSUE THREAD

**Issue by VoidSparda** [Maia-Everett/dalamud-snooper#4]
Hi!

Due to the recent major patch, looks like the plugin will require an update for Api7. Just wanted to bring notice since I really love your plugin with it helping my scatterbrained roleplaying. No rush of course if you're busy or for any other reason.

**Comment by Maia-Everett** [comment]
I'm on it! I've ported the plugin, but while I'm at it, I'm going to implement a couple new features before submitting it for publication today.

**Comment by VoidSparda** [comment]
That's fantastic to hear! I was personally just curious but didn't want to come off as pushy like some of other folks can be after updates like these. 

But greatly looking forward to it and the new features! And thank you for this plugin as a whole too, was an actual life changer haha.

**Comment by Maia-Everett** [comment]
Snooper 0.3.0.0 has now been published. Enjoy!
