### ISSUE TITLE
Self party messages

### ISSUE THREAD

**Issue by iv230** [Maia-Everett/dalamud-snooper#5]
It looks like our own messages sent in party channel are not displayed when targeting ourself or adding ourself to a separate window. other player messages in this chanel are written correctly.

**Comment by gucciBane** [comment]
This explains a lot, actually. I kept wondering what was happening there.

**Comment by iv230** [comment]
Still not fixed

**Comment by Maia-Everett** [comment]
It's on my list, sorry! Hopefully I'll get to it this week.

**Comment by Maia-Everett** [comment]
Fixed in 1.1.0.0.
