### ISSUE TITLE
Font Too Small

### ISSUE THREAD

**Issue by teutelquessir** [Maia-Everett/dalamud-snooper#6]
I'm old and I wear bifocals.  It's almost impossible for me to read the tiny font.  Can there please be some option added to increase the font size?  I run my normal FFXIV font at 20 pt to give you an idea of what my issue is.  Thank you! <3

**Comment by Maia-Everett** [comment]
Hello!

The option to increase font size is already in Snooper configuration. You can access it through the Dalamud Plugins window.

You can also globally increase font size for all Dalamud windows through the Dalamud Settings window.
