### ISSUE TITLE
Hope that can show what I said

### ISSUE THREAD

**Issue by HeavenPolicy** [Maia-Everett/dalamud-snooper#8]
Helllo, This plugin works great on RP, hope to add new features, very thanks.

Hope to add new choose:

Can follow several speakers at the same time.
Can also choose to display your own speech content in the window.
Can export the chat content as a screenshot or text file

(This text is translated by Google, if there is a phenomenon that the sentence does not make sense, I am very sorry)

**Comment by Maia-Everett** [comment]
All done in 1.1.0.0.
